version: '3.9'

services:
  app:
    build: .
    ports:
      - '8000:8000'
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    # TODO: add mlflow, postgres, minio, prometheus, grafana when implementation starts.
