artifact_location: file:///home/andrn/TS-2/mlflow/571089774038325513
creation_time: 1780220535124
experiment_id: '571089774038325513'
last_update_time: 1780220535124
lifecycle_stage: active
name: liquidity_forecast
trace_location: null
workspace: default
